# Generated by Django 3.2.3 on 2021-05-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
